import Head from "next/head";
import { Col, Row } from "reactstrap";
// import SalesChart from "../src/components/dashboard/SalesChart";
import Feeds from "../src/components/dashboard/Feeds";
import ProjectTables from "../src/components/dashboard/ProjectTable";
import TopCards from "../src/components/dashboard/TopCards";
import Blog from "../src/components/dashboard/Blog";
import bg1 from "../src/assets/images/bg/bg1.jpg";
import bg2 from "../src/assets/images/bg/bg2.jpg";
import bg3 from "../src/assets/images/bg/bg3.jpg";
import bg4 from "../src/assets/images/bg/bg4.jpg";
import FullLayout from "../src/layouts/FullLayout";
import { useEffect, useState } from "react";

const BlogData = [
  {
    image: bg1,
    title: "This is simple blog",
    subtitle: "2 comments, 1 Like",
    description:
      "This is a wider card with supporting text below as a natural lead-in to additional content.",
    btnbg: "primary",
  },
  {
    image: bg2,
    title: "Lets be simple blog",
    subtitle: "2 comments, 1 Like",
    description:
      "This is a wider card with supporting text below as a natural lead-in to additional content.",
    btnbg: "primary",
  },
  {
    image: bg3,
    title: "Don't Lamp blog",
    subtitle: "2 comments, 1 Like",
    description:
      "This is a wider card with supporting text below as a natural lead-in to additional content.",
    btnbg: "primary",
  },
  {
    image: bg4,
    title: "Simple is beautiful",
    subtitle: "2 comments, 1 Like",
    description:
      "This is a wider card with supporting text below as a natural lead-in to additional content.",
    btnbg: "primary",
  },
];

export default function Home() {
  useEffect(() => {
    if (!localStorage.getItem('authToken')) {
      window.location.href = '/auth/login';
    }
  }, []);
  const [dashboardInsights, setDashboardInsights] = useState({
    hospitalCount: '0',
    planCount: '0',
    userCount: '0',
    insuranceCount: '0',
  });
  const fetchDashboardInsights = async () => {
    try {
      const res = await fetch("https://insurance-server-ten.vercel.app/api/insurance/dashboard");
      const data = await res.json();
      if (data?.status) {
        setDashboardInsights(data?.data)
      } else {
        alert("Error fetching data");
      }
    } catch (error) {
      console.log(error);
    }
  };
  useEffect(() => {
    fetchDashboardInsights(); 
  }, [])
  return (
    <div>
      <FullLayout>
        <Head>
          <title>Health And Insurance System</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>
          <Row>
            <Col sm="6" lg="3">
              <TopCards
                bg="bg-light-success text-success"
                title="Profit"
                subtitle="Hospitals"
                earning={dashboardInsights?.hospitalCount}
                icon="bi bi-bandaid-fill"
              />
            </Col>
            <Col sm="6" lg="3">
              <TopCards
                bg="bg-light-danger text-danger"
                title="Refunds"
                subtitle="(Availed)"
                earning={dashboardInsights?.insuranceCount}
                icon="bi bi-coin"
              />
            </Col>
            <Col sm="6" lg="3">
              <TopCards
                bg="bg-light-warning text-warning"
                title="New Project"
                subtitle="Customers"
                earning={dashboardInsights?.userCount}
                icon="bi bi-basket3"
              />
            </Col>
            <Col sm="6" lg="3">
              <TopCards
                bg="bg-light-info text-into"
                title="Sales"
                subtitle="Total Plans"
                earning={dashboardInsights?.planCount}
                icon="bi bi-bag"
              />
            </Col>
          </Row>
        </div>
      </FullLayout >
    </div>
  );
}
